# Generated by Django 3.1 on 2020-08-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200829_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='photo',
            field=models.CharField(default='default.png', help_text='Enter name of image of your director', max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='avatar',
            field=models.CharField(default='default.png', help_text='Enter name of image of your film', max_length=100),
        ),
    ]
